image: "rust:latest"

stages:
    - build
    - test

before_script:
    - rustup toolchain add nightly
    - rustup target add x86_64-unknown-redox --toolchain nightly
    - rustup show

variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo/

cache:
    paths:
        - target/
        - .cargo/

# This exists b/c it will give compiler errors beyond the type errors
#   b/c of syscall.
build:linux:cargo:
    stage: build
    script:
        - cargo +nightly build --verbose
    allow_failure: true

build:redox:cargo:
    stage: build
    before_script:
        - apt-get update -qq
        - apt-get install -qq apt-transport-https
        - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F
        - add-apt-repository 'deb https://static.redox-os.org/toolchain/apt /'
        - apt-get update -qq && apt-get install -qq x86-64-unknown-redox-gcc
    script:
        - cargo +nightly build --verbose --target x86_64-unknown-redox
