[package]
name = "init"
description = "Init system for redox, includes service management"
version = "0.1.0"

[dependencies]
failure = "0.1"
generational-arena = "0.2"
log = "0.4"
redox_syscall = "0.1"
serde = "1.0"
serde_derive = "1.0"
simple_logger = "1.0"
toml = "0.4"
